[project]
name = "toy-qwen3-moe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.5",
    "torch>=2.7.1",
    "tqdm>=4.67.1",
]
